name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t devops-demo-app .

    - name: Deploy to Kubernetes
      run: kubectl rollout restart deployment devops-app